# Generated by Django 6.0.3 on 2026-05-29 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athidhi_holidays_app', '0009_property_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tourist_place',
        ),
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='athidhi_holidays_app.property'),
        ),
    ]
